### ISSUE TITLE
Alternative for virtualbox

### ISSUE THREAD

**Issue by matijag** [geerlingguy/ansible-for-kubernetes#14]
All the examples assume vagrant will use virtualbox. 
However, Debian has decided against including virtualbox in it's version 10 (https://wiki.debian.org/VirtualBox , https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794466).

The solution is fairly simple, just make vagrant use virt-manager, so I think it's worth at least a mention.

https://computingforgeeks.com/using-vagrant-with-libvirt-on-linux/
https://stackoverflow.com/questions/42155213/using-vagrant-to-set-up-a-vm-with-kvm-qemu-without-virtualbox

**Comment by geerlingguy** [comment]
The only reason I standardize on VirtualBox is that it has been rock solid across Windows, macOS, and most Linux distros for over a decade, and is a good 'lowest common denominator'. Note that any playbook example can be run completely standalone against any local VM, you don't need to use Vagrant or VirtualBox at all if you don't want.

I just don't have the bandwidth to try to support different types of virtualization tech stacks that don't run universally on Windows/Mac/Linux, but I try to make sure it is as simple as possible to adapt my `Vagrantfile`s and playbooks to run on any kind of machine.

So at this time, I'm going to close this as 'won't fix', since I believe you can still download and install the latest versions of VirtualBox for Debian outside of the official apt repos for Debian.
