### ISSUE TITLE
Chapter 4 - Vagrant file description: pg 72

### ISSUE THREAD

**Issue by js-mode** [geerlingguy/ansible-for-kubernetes#55]
At the bottom of page 72 you describe the Vagrant file with: 

`Defines a lit of ‘boxes’, kube1, kube2, and kube3, which will get IP addresses in the range 192.168.7.[2-4].`

Did you meant to say `list of boxes` instead?

**Comment by js-mode** [comment]
Any chance you are going to be able to do a chapter for Azure Kubernetes as well? Trying to only use Azure instead of AWS and wondering how different the two environments are.

**Comment by geerlingguy** [comment]
@js-mode - Well those boxes are _lit_ 🔥 hehe

Anyways, yes, I meant to say `list` there. I'll get this corrected soon.

I am not yet sure if I'm going to do something on AKS, just because of all the platforms, I'm the least familiar with Azure and short of Microsoft kicking in some sort of sponsorship, I'm not that inclined to try it out unless a specific need arises.

**Comment by geerlingguy** [comment]
Ah I just realized #64 was for this same particular bug. I fixed it in the manuscript but I'll give you credit as well since you were the first to spot it :)
