### ISSUE TITLE
Chapter 1 - Kubernetes Cluster Cleanup 

### ISSUE THREAD

**Issue by SteveJM** [geerlingguy/ansible-for-kubernetes#58]
You offer sage advice "Treat your Kubernetes cluster servers like cattle and not pets".

However, no cleanup / teardown guide is given. In trying to tear everything down (following much Googling). I've now got a cluster that won't allow anything to join the (new) mater and nodes that timeout trying to connect with no idea how to sort out this mess by taking everything back to ground zero.

NB: Thee instructions near the end of chapter 1 for removing docker images - which is not hard to find via Google / is considered Docker 101 in any event.

**Comment by SteveJM** [comment]
I've tried uninstalling all kubernetes software from the servers and re-running the playbook (which includes the install).

It still fails when the nodes try and join the master. Basically they timeout.

The very first time they did join - but then I realised that the flannel network was not what I wanted. So I reconfigured to use Calico. But you can't just re-run the playbook - the IP addresses have already been asssigned and now don't match the CIDR for Calico. So I tore everything down to try and get fresh IP addresses. That is when my fun started as the nodes would not join after that.

So I dud a complete uninstall.

Still no joy.

**Comment by geerlingguy** [comment]
@SteveJM - Did you ever find a resolution for this?

When I mention treating the cluster like cattle and not pets, I also mean the instances themselves—e.g. even when I'm building bare metal Pi clusters, I will frequently re-flash each Pi's OS image from scratch to make sure that I can rebuild the cluster entirely.

I don't usually add clean uninstall instructions or automation because my method is "delete everything, reformat, build from the ground up again", which forces me to have 100% automation for every step of the process (including networking setup).
