### ISSUE TITLE
[section_request] deploy WAR to OpenShift 4

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-for-kubernetes#6]
One ops-team takes care of the corporate OpenShift clusters, yet tens to hundreds of Java dev-teams want to use it. Please describe a portable workflow for an application development pipeline.

**Comment by geerlingguy** [comment]
@bbaassssiiee - Deploying custom Java apps (especially on a more turnkey K8s distro like OpenShift) sounds like something a lot of readers would like to do. Do you have any good example Java applications I could use as an example to deploy? I am familiar mostly with Apache Solr, but haven't dealt _too_ much with other Java apps (besides maybe ElasticSearch, but I know less about it besides 'getting it running' and 'trying to feed it more resources because it's falling over' ;).

**Comment by geerlingguy** [comment]
(Also noting as a general aside: It is _extremely_ difficult to work with OpenShift 4, IMO—it is hard to bring up a test cluster quickly (even if you give the installer full access to your AWS account), and it is frustrating how long it takes and how much of my computer it eats up, trying to run CRC locally too... therefore I am mostly limiting my time generating OpenShift-specific examples until there's some way of deploying it that's as simple as Kind or Minikube.)

**Comment by bbaassssiiee** [comment]
Maybe this demo app from the book about Jenkins? https://github.com/wakaleo/game-of-life

**Comment by bbaassssiiee** [comment]
Many people can use a managed k8s, and can assume the cluster to be up. Either in Azure, GCP or AWS.

**Comment by bbaassssiiee** [comment]
Take a look at this https://developer.ibm.com/technologies/devops/tutorials/orchestrate-multi-tier-application-deployments-on-kubernetes-using-ansible-pt-3/

**Comment by bbaassssiiee** [comment]
https://developers.redhat.com/blog/2019/09/05/red-hat-openshift-4-on-your-laptop-introducing-red-hat-codeready-containers/

**Comment by bbaassssiiee** [comment]
Ok, I give up.

**Comment by geerlingguy** [comment]
I'm just less interested in OpenShift 4 since it's a lot of work to try to get an instance running (compared to minikube, kind, etc. for plain Kubernetes). Someday if the OpenShift/OKD team can get a way for devs to build quick test clusters, I'd be more interested in working with it, but as it is I just don't have the time/resources (especially since I couldn't test this stuff in CI without building a separate backend to run the tests).
