### ISSUE TITLE
microk8 instead of minikube for development?

### ISSUE THREAD

**Issue by timoc** [geerlingguy/ansible-for-kubernetes#76]
Microk8 seems like a better alternative to minikube as a lightweight cross platform development tool. It has raspberry pi and other personal cluster deployment opportunities.  Could you cover that?

**Comment by geerlingguy** [comment]
@timoc - I will likely discuss a few different distributions, including k3s, Microk8s, k0s, and more. Right now I'm using Minikube in my Kubernetes 101 series a little bit just because of a few of the features it offers for services and ingress built-in. I will be using other distros as needed when the examples I use fit their model of usage.

Thanks!
